### ISSUE TITLE
Error Creating New Acronym or User Due to Missing id Key in POST Request

### ISSUE THREAD

**Issue by banghuazhao** [kodecocodes/vpr-materials#33]
Hi,

I’m encountering an issue when trying to create a new acronym or user in the following chapters (using editions/3.0 branch):

* Chapter 7: POST http://localhost:8080/api/acronyms/
* Chapter 9: POST http://localhost:8080/api/users

The request fails with the following error:
```json
{
    "reason": "No such key 'id' at path ''. No value associated with key \"id\".",
    "error": true
}
```

It seems the error occurs because the Acronym and User models fail to decode due to the missing id key. However, if I manually assign a UUID to the id in the POST request, the creation is successful.

Environment:
* Swift 5.10
* Vapor: 4.105.0

A screenshot of the error is attached for reference.

<img width="948" alt="Screenshot 2024-09-03 at 11 09 28 PM" src="https://github.com/user-attachments/assets/0c59032d-dd98-4d20-9a60-36f1cd6c3f0b">

<img width="968" alt="Screenshot 2024-09-03 at 11 14 27 PM" src="https://github.com/user-attachments/assets/24c059eb-8e44-4ecc-9a56-389465e77f10">

**Comment by 0xTim** [comment]
Have you tried sending JSON instead?

**Comment by banghuazhao** [comment]
Hi @0xTim,
I tried sending the data as JSON instead, and it worked perfectly! 
Sorry for the confusion 😅 — It turns out the issue was with Postman, where the form-data key-value pairs in the Body didn’t correctly represent JSON.
Thanks for your help!
